### PR TITLE
Added getter for all child element xpaths

### PR DESCRIPTION
**Pull request by RlanderRISCSW**
For the CPACS code generator cpacs_tigl_gen we need a possibility to iterate over all child elements of an element in the order of appearance. Therefore I propose the following extension of the tixi cpp interface.

### CODE REVIEW

**Comment by rainman110** [comment]
Sieht gut aus!

**Comment by rainman110** [comment]
@RlanderRISCSW Kannst du bitte noch tests for die neuen Funktionen hinzufügen?

**Comment by RlanderRISCSW** [comment]
sorry, didn't recognize that there were tests for the cpp wrapper

**Comment by rainman110** [comment]
Perfect!

**Pull request merged**
