### PR TITLE
Fixed crash when printing too long status messages

### LINKED ISSUE #108: Exception message too big
In the C++ wrapper the function
```
TixiDocumentHandle TixiImportFromString(const std::string& xml)
```
throws an exception if the document could not be constructed (e.g. not well formed). The exception message contains the XML string passed to the function, which might be very large.

In my case, I put the error message in a dialog box and the message's length leads to rendering errors of the dialog box. Although I could solve this issue by shortening the error message myself, I think others might have similar issues when printing the exception message somewhere.

I therefore suggest to remove the xml string from the exception message.

### PR DESCRIPTION
**Pull request by rainman110**
We still do not disable printing long messages when loading an invalid xml file. This could be handled in a separate PR if required.

I reproduced and verified the issue with valgrind. After the fix, valgrind shows no errors enymore.

This commit fixes #108

### CODE REVIEW

**Comment by rainman110** [comment]
@RlanderRISCSW Can you please check, whether this issue is fixed for you?

**Comment by joergbrech** [comment]
I don't exactly understand what has changed: Withouth the changes in `src/tixiImpl.c` the new test case succeeds as well.

I don't think you need to reinitialize `varArgs` and according to http://www.cplusplus.com/reference/cstdarg/va_end/ it suffices to call `va_end` once before the function returns.

**Comment by rainman110** [comment]
Without the changes, I get a valgrind error. I think it was exactly the problem not the reinitialize the varargs. In the old code, the len variable was too small resulting in an invalid memory access.

**Comment by joergbrech** [comment]
Here is my valgrind output (I am using the old `tixiImpl.c`, but keep the new unit test):

```
me@my-computer:~/data/code/tixi/build/tests$ valgrind ./TIXI-unittests --gtest_filter=*printMessageCrash*
==27236== Memcheck, a memory error detector
==27236== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==27236== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==27236== Command: ./TIXI-unittests --gtest_filter=*printMessageCrash*
==27236== 
Note: Google Test filter = *printMessageCrash*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Bugs
[ RUN      ] Bugs.printMessageCrash
[       OK ] Bugs.printMessageCrash (4 ms)
[----------] 1 test from Bugs (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (27 ms total)
[  PASSED  ] 1 test.
==27236== 
==27236== HEAP SUMMARY:
==27236==     in use at exit: 104 bytes in 1 blocks
==27236==   total heap usage: 4,366 allocs, 4,365 frees, 377,089 bytes allocated
==27236== 
==27236== LEAK SUMMARY:
==27236==    definitely lost: 0 bytes in 0 blocks
==27236==    indirectly lost: 0 bytes in 0 blocks
==27236==      possibly lost: 0 bytes in 0 blocks
==27236==    still reachable: 104 bytes in 1 blocks
==27236==         suppressed: 0 bytes in 0 blocks
==27236== Rerun with --leak-check=full to see details of leaked memory
==27236== 
==27236== For lists of detected and suppressed errors, rerun with: -s
==27236== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by rainman110** [comment]
And this is my output 

```
 ./TIXI-unittests --gtest_filter=Bugs.printMessageCrash
Note: Google Test filter = Bugs.printMessageCrash
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Bugs
[ RUN      ] Bugs.printMessageCrash
Segmentation fault
```

And here the valgrind stuff:

```
==31970== Memcheck, a memory error detector
==31970== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==31970== Using Valgrind-3.16.0 and LibVEX; rerun with -h for copyright info
==31970== Command: ./TIXI-unittests --gtest_filter=Bugs.printMessageCrash
==31970== 
Note: Google Test filter = Bugs.printMessageCrash
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Bugs
[ RUN      ] Bugs.printMessageCrash
==31970== Invalid read of size 1
==31970==    at 0x4035952: strlen (vg_replace_strmem.c:459)
==31970==    by 0x5AC44D2: vfprintf (vfprintf.c:1643)
==31970==    by 0x5AEF90F: vsnprintf (vsnprintf.c:114)
==31970==    by 0x3658CC: printMsg (tixiImpl.c:72)
==31970==    by 0x2CF7E9: Bugs_printMessageCrash_Test::TestBody() (test_bugs.cpp:78)
==31970==    by 0x34FED9: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2443)
==31970==    by 0x34732C: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2479)
==31970==    by 0x311F4D: testing::Test::Run() (gtest.cc:2517)
==31970==    by 0x312EC3: testing::TestInfo::Run() (gtest.cc:2693)
==31970==    by 0x31385A: testing::TestCase::Run() (gtest.cc:2811)
==31970==    by 0x326098: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5177)
==31970==    by 0x351811: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2443)
==31970==  Address 0x20 is not stack'd, malloc'd or (recently) free'd
==31970== 
==31970== 
==31970== Process terminating with default action of signal 11 (SIGSEGV)
==31970==  Access not within mapped region at address 0x20
==31970==    at 0x4035952: strlen (vg_replace_strmem.c:459)
==31970==    by 0x5AC44D2: vfprintf (vfprintf.c:1643)
==31970==    by 0x5AEF90F: vsnprintf (vsnprintf.c:114)
==31970==    by 0x3658CC: printMsg (tixiImpl.c:72)
==31970==    by 0x2CF7E9: Bugs_printMessageCrash_Test::TestBody() (test_bugs.cpp:78)
==31970==    by 0x34FED9: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2443)
==31970==    by 0x34732C: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2479)
==31970==    by 0x311F4D: testing::Test::Run() (gtest.cc:2517)
==31970==    by 0x312EC3: testing::TestInfo::Run() (gtest.cc:2693)
==31970==    by 0x31385A: testing::TestCase::Run() (gtest.cc:2811)
==31970==    by 0x326098: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5177)
==31970==    by 0x351811: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2443)
==31970==  If you believe this happened as a result of a stack
==31970==  overflow in your program's main thread (unlikely but
==31970==  possible), you can try to increase the size of the
==31970==  main thread stack using the --main-stacksize= flag.
==31970==  The main thread stack size used in this run was 8388608.
==31970== 
==31970== HEAP SUMMARY:
==31970==     in use at exit: 187,177 bytes in 1,674 blocks
==31970==   total heap usage: 4,359 allocs, 2,685 frees, 374,498 bytes allocated
==31970== 
==31970== LEAK SUMMARY:
==31970==    definitely lost: 0 bytes in 0 blocks
==31970==    indirectly lost: 0 bytes in 0 blocks
==31970==      possibly lost: 0 bytes in 0 blocks
==31970==    still reachable: 187,177 bytes in 1,674 blocks
==31970==         suppressed: 0 bytes in 0 blocks
==31970== Rerun with --leak-check=full to see details of leaked memory
==31970== 
==31970== For lists of detected and suppressed errors, rerun with: -s
==31970== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault
```

**Comment by rainman110** [comment]
This output is using the previous commit without the fix.

**Comment by joergbrech** [comment]
Ok so its one segfault on your machine without the fix vs no segfault with the fix on both our machines :shrug: The fix wins! :wink:

**Comment by joergbrech** [comment]
FYI: I do get a segfault for a debug build without the fix

**Pull request merged**
