### PR TITLE
bugfix in python wrapper

### LINKED ISSUE #105: The TiGL python example fails due to TIXI errors
There is a bug in the python wrapper for TIXI, some of the functions are missing the `tixi` prefix

### PR DESCRIPTION
**Pull request by joergbrech**
some of the functions were missing the tixi prefix

fixes #105

### CODE REVIEW

**Comment by rainman110** [comment]
This completely changes the API! Actually, none of the functions should have the tixi prefix!

**Comment by ArneBachmann** [comment]
Add new api, add deprecation warning until next Major release, then remove old api

**Comment by rainman110** [comment]
@ArneBachmann The API actually has not changed between tixi 2 and 3!

**Comment by ArneBachmann** [comment]
I wouldn't know as I never used tixi. What I hinted on was introducing the API change that we talked about in the pull request (either removing *all* tixi prefixes or aligning all functions to *all have* a tixi prefix) in a smart way using deprecation warnings between releases.

**Pull request closed without merging**
